[build-system]
requires = [
    "setuptools",
    "torch",
]
build-backend = "setuptools.build_meta"

[project]
name = "hilt"
dynamic = ["version", "description", "readme", "dependencies", "urls"]

[project.scripts]
profile-kernel = "tools.profile_kernel:main"
